# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qicode/proto/cell.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "qicode/proto/cell.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17qicode/proto/cell.proto\x12\x0cqicode.proto"\x15\n\x04\x43\x65ll\x12\r\n\x05index\x18\x01 \x01(\r"\x18\n\x07\x43oupler\x12\r\n\x05index\x18\x01 \x01(\rb\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "qicode.proto.cell_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CELL"]._serialized_start = 41
    _globals["_CELL"]._serialized_end = 62
    _globals["_COUPLER"]._serialized_start = 64
    _globals["_COUPLER"]._serialized_end = 88
# @@protoc_insertion_point(module_scope)
