# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balunatten.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import qiclib.packages.grpc.datatypes_pb2 as datatypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x62\x61lunatten.proto\x12\nbalunatten\x1a\x0f\x64\x61tatypes.proto"\\\n\x07\x43hannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\r\x12&\n\x04type\x18\x02 \x01(\x0e\x32\x18.balunatten.Channel.Type"\x18\n\x04Type\x12\x07\n\x03\x41\x44\x43\x10\x00\x12\x07\n\x03\x44\x41\x43\x10\x01"=\n\x06Number\x12$\n\x07\x63hannel\x18\x01 \x01(\x0b\x32\x13.balunatten.Channel\x12\r\n\x05value\x18\x02 \x01(\r"<\n\x05\x46loat\x12$\n\x07\x63hannel\x18\x01 \x01(\x0b\x32\x13.balunatten.Channel\x12\r\n\x05value\x18\x02 \x01(\x02\x32\xed\x02\n\x11\x42\x61lUnAttenService\x12\x39\n\x0eSetAttenuation\x12\x11.balunatten.Float\x1a\x14.sdr.datatypes.Empty\x12;\n\x0eGetAttenuation\x12\x13.balunatten.Channel\x1a\x14.sdr.datatypes.Float\x12\x36\n\tSwitchOff\x12\x13.balunatten.Channel\x1a\x14.sdr.datatypes.Empty\x12\x39\n\rSwitchNyquist\x12\x12.balunatten.Number\x1a\x14.sdr.datatypes.Empty\x12\x36\n\nGetNyquist\x12\x13.balunatten.Channel\x1a\x13.sdr.datatypes.UInt\x12\x35\n\x08SwitchDC\x12\x13.balunatten.Channel\x1a\x14.sdr.datatypes.Emptyb\x06proto3'
)


_CHANNEL = DESCRIPTOR.message_types_by_name["Channel"]
_NUMBER = DESCRIPTOR.message_types_by_name["Number"]
_FLOAT = DESCRIPTOR.message_types_by_name["Float"]
_CHANNEL_TYPE = _CHANNEL.enum_types_by_name["Type"]
Channel = _reflection.GeneratedProtocolMessageType(
    "Channel",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHANNEL,
        "__module__": "balunatten_pb2"
        # @@protoc_insertion_point(class_scope:balunatten.Channel)
    },
)
_sym_db.RegisterMessage(Channel)

Number = _reflection.GeneratedProtocolMessageType(
    "Number",
    (_message.Message,),
    {
        "DESCRIPTOR": _NUMBER,
        "__module__": "balunatten_pb2"
        # @@protoc_insertion_point(class_scope:balunatten.Number)
    },
)
_sym_db.RegisterMessage(Number)

Float = _reflection.GeneratedProtocolMessageType(
    "Float",
    (_message.Message,),
    {
        "DESCRIPTOR": _FLOAT,
        "__module__": "balunatten_pb2"
        # @@protoc_insertion_point(class_scope:balunatten.Float)
    },
)
_sym_db.RegisterMessage(Float)

_BALUNATTENSERVICE = DESCRIPTOR.services_by_name["BalUnAttenService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _CHANNEL._serialized_start = 49
    _CHANNEL._serialized_end = 141
    _CHANNEL_TYPE._serialized_start = 117
    _CHANNEL_TYPE._serialized_end = 141
    _NUMBER._serialized_start = 143
    _NUMBER._serialized_end = 204
    _FLOAT._serialized_start = 206
    _FLOAT._serialized_end = 266
    _BALUNATTENSERVICE._serialized_start = 269
    _BALUNATTENSERVICE._serialized_end = 634
# @@protoc_insertion_point(module_scope)
