# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digital_trigger.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'digital_trigger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import qiclib.packages.grpc.datatypes_pb2 as datatypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64igital_trigger.proto\x12\x0f\x64igital_trigger\x1a\x0f\x64\x61tatypes.proto\"L\n\x0cTriggerIndex\x12+\n\x05index\x18\x01 \x01(\x0b\x32\x1c.sdr.datatypes.EndpointIndex\x12\x0f\n\x07trigger\x18\x02 \x01(\r\"J\n\x0bOutputIndex\x12+\n\x05index\x18\x01 \x01(\x0b\x32\x1c.sdr.datatypes.EndpointIndex\x12\x0e\n\x06output\x18\x02 \x01(\r\"P\n\nTriggerSet\x12\x12\n\ncontinuous\x18\x01 \x01(\x08\x12\x17\n\x0f\x64uration_cycles\x18\x02 \x01(\r\x12\x15\n\routput_select\x18\x03 \x03(\r\"k\n\x11IndexedTriggerSet\x12,\n\x05index\x18\x01 \x01(\x0b\x32\x1d.digital_trigger.TriggerIndex\x12(\n\x03set\x18\x02 \x01(\x0b\x32\x1b.digital_trigger.TriggerSet\"T\n\x0cOutputConfig\x12+\n\x05level\x18\x01 \x01(\x0e\x32\x1c.digital_trigger.OutputLevel\x12\x17\n\x0f\x64uration_cycles\x18\x02 \x01(\r\"q\n\x13IndexedOutputConfig\x12+\n\x05index\x18\x01 \x01(\x0b\x32\x1c.digital_trigger.OutputIndex\x12-\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1d.digital_trigger.OutputConfig*.\n\x0bOutputLevel\x12\x0e\n\nACTIVE_LOW\x10\x00\x12\x0f\n\x0b\x41\x43TIVE_HIGH\x10\x01\x32\x93\x04\n\x15\x44igitalTriggerService\x12;\n\x05Reset\x12\x1c.sdr.datatypes.EndpointIndex\x1a\x14.sdr.datatypes.Empty\x12I\n\rSetTriggerSet\x12\".digital_trigger.IndexedTriggerSet\x1a\x14.sdr.datatypes.Empty\x12K\n\rGetTriggerSet\x12\x1d.digital_trigger.TriggerIndex\x1a\x1b.digital_trigger.TriggerSet\x12\x46\n\x10\x43learTriggerSets\x12\x1c.sdr.datatypes.EndpointIndex\x1a\x14.sdr.datatypes.Empty\x12M\n\x0fSetOutputConfig\x12$.digital_trigger.IndexedOutputConfig\x1a\x14.sdr.datatypes.Empty\x12N\n\x0fGetOutputConfig\x12\x1c.digital_trigger.OutputIndex\x1a\x1d.digital_trigger.OutputConfig\x12>\n\x07Trigger\x12\x1d.digital_trigger.TriggerIndex\x1a\x14.sdr.datatypes.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digital_trigger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OUTPUTLEVEL']._serialized_start=605
  _globals['_OUTPUTLEVEL']._serialized_end=651
  _globals['_TRIGGERINDEX']._serialized_start=59
  _globals['_TRIGGERINDEX']._serialized_end=135
  _globals['_OUTPUTINDEX']._serialized_start=137
  _globals['_OUTPUTINDEX']._serialized_end=211
  _globals['_TRIGGERSET']._serialized_start=213
  _globals['_TRIGGERSET']._serialized_end=293
  _globals['_INDEXEDTRIGGERSET']._serialized_start=295
  _globals['_INDEXEDTRIGGERSET']._serialized_end=402
  _globals['_OUTPUTCONFIG']._serialized_start=404
  _globals['_OUTPUTCONFIG']._serialized_end=488
  _globals['_INDEXEDOUTPUTCONFIG']._serialized_start=490
  _globals['_INDEXEDOUTPUTCONFIG']._serialized_end=603
  _globals['_DIGITALTRIGGERSERVICE']._serialized_start=654
  _globals['_DIGITALTRIGGERSERVICE']._serialized_end=1185
# @@protoc_insertion_point(module_scope)
